#!/usr/bin/env bash
# Loads the Neovim config headless, the way a first start on a new machine
# does: lazy.nvim bootstraps itself and installs the plugins lazy-lock.json
# pins, then a second start loads every plugin (the lazy-loaded ones too) and
# fails on any error. Then once more with each flavor's colors.sh, as
# fdwm-theme writes it, to check the colors follow the palette. Uses its own
# config and data dirs, not yours.
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd)

if ! nvim --clean --headless +'if !has("nvim-0.12") | cquit | endif' +qa; then
    echo "The config needs Neovim 0.12 or newer; this is $(nvim --version | head -1)" >&2
    exit 1
fi

T=$(mktemp -d)
# (|| true: parser downloads nvim-treesitter started can outlive the quit
# and still be writing into $T, so rm may not get all of it; that's no
# failure of the config)
trap 'rm -rf "$T" || true' EXIT
export XDG_CONFIG_HOME=$T/config XDG_DATA_HOME=$T/data XDG_STATE_HOME=$T/state XDG_CACHE_HOME=$T/cache
mkdir -p "$XDG_CONFIG_HOME"
cp -r "$ROOT/dotfiles/.config/nvim" "$XDG_CONFIG_HOME/"

echo "== first start: install the pinned plugins"
nvim --headless '+Lazy! restore' +qa

echo "== second start: load everything"
nvim --headless --cmd "luafile $ROOT/tests/nvim-check.lua"

# the flavors in the palette's header line, generated by a copy of
# fdwm-theme (so nothing is written into the checkout)
mapfile -t flavors < <(awk '$1 == "name" { for (i = 2; i <= NF; i++) print $i; exit }' "$ROOT/palette")
mkdir -p "$T/repo/suckless" "$XDG_CONFIG_HOME/fdwm"
cp "$ROOT/fdwm-theme" "$ROOT/palette" "$T/repo/"
cp -r "$ROOT/grub" "$ROOT/dunst" "$T/repo/"
for flavor in "${flavors[@]}"; do
    echo "== with fdwm-theme's $flavor colors"
    echo "$flavor" >"$XDG_CONFIG_HOME/fdwm/flavor"
    bash "$T/repo/fdwm-theme" generate >/dev/null
    # shellcheck source=/dev/null
    . "$XDG_CONFIG_HOME/fdwm/colors.sh"
    if ! out=$(nvim --headless --cmd "luafile $ROOT/tests/nvim-check.lua" 2>&1); then
        echo "$out"
        exit 1
    fi
    echo "$out"
    grep -qx "colorscheme catppuccin-mocha" <<<"$out" || {
        echo "the colorscheme isn't catppuccin-mocha" >&2
        exit 1
    }
    # shellcheck disable=SC2154  # fdwm_* come from colors.sh
    grep -qx "normal $fdwm_text on $fdwm_base" <<<"$out" || {
        echo "Neovim's text and background aren't $flavor's text and base" >&2
        exit 1
    }
done
