#!/usr/bin/env bash
# shellcheck disable=SC2154  # fdwm_* come from the generated colors.sh
# fdwm-theme generate: every palette entry in colors.h and colors.sh, names
# looked up, in the flavor saved in ~/.config/fdwm/flavor; the GRUB theme
# and its selection image; and a clear error for a palette, template or
# flavor it can't use.
# shellcheck source=tests/lib.sh
source "$(dirname "$0")/lib.sh"
sandbox
theme_repo "$T/repo"
gen() { HOME=$T/home bash "$T/repo/fdwm-theme" generate 2>&1; }
h=$T/repo/suckless/colors.h
colors=$T/home/.config/fdwm/colors.sh

# check_flavor FLAVOR COLUMN: after generating, every entry of the palette's
# COLUMN (2 for its first flavor), names looked up, in colors.h and colors.sh
check_flavor() {
    local entries name value v w want bad=
    out=$(gen)
    expect "$1: generate exits 0" 0 "$?"
    expect_match "$1: says what it wrote" "^Generated the $1 colors" "$out"
    # shellcheck source=/dev/null
    . "$colors"
    expect "$1: colors.sh names the flavor" "$1" "$fdwm_flavor"
    entries=$(sed 's/#.*//' "$T/repo/palette" | awk -v c="$2" 'NF && $1 != "name" { print $1, $c }')
    expect "$1: colors.h has one define per palette entry" "$(wc -l <<<"$entries")" "$(grep -c '^#define COL_' "$h")"
    while read -r name value; do
        v=fdwm_$name
        # a name in place of a color: that color
        if [[ $value =~ ^[0-9a-f]{6}$ ]]; then want=$value; else w=fdwm_$value; want=${!w#\#}; fi
        [[ ${!v:-} == "#$want" ]] || bad+=" colors.sh:$name"
        grep -qx "#define COL_${name^^} \"#$want\"" "$h" || bad+=" colors.h:$name"
    done <<<"$entries"
    expect "$1: every entry, names looked up, in colors.h and colors.sh" "" "$bad"
    expect_match "$1: the kernel's console background is term_bg" \
        "^vt\.default_red=$((16#${fdwm_term_bg:1:2})),.* vt\.default_blu=$((16#${fdwm_term_bg:5:2}))," \
        "$(HOME=$T/home bash "$T/repo/fdwm-theme" kernel-args)"
}

mkdir -p "$T/home/.config/fdwm"
echo latte >"$T/home/.config/fdwm/flavor"
check_flavor latte 3
latte_base=$fdwm_base
echo nosuch >"$T/home/.config/fdwm/flavor"
out=$(gen)
expect "an unknown flavor saved: fails" 1 "$?"
expect_match "an unknown flavor saved: names the ones there are" "no nosuch column \(its flavors: +mocha +latte\)" "$out"
rm "$T/home/.config/fdwm/flavor"
check_flavor mocha 2
expect "no flavor saved: mocha, not what was generated last" yes "$([[ $fdwm_base != "$latte_base" ]] && echo yes)"

expect_match "colors.h says it is generated" '^/\* Generated by fdwm-theme' "$(head -n1 "$h")"
expect_match "colors.sh says it is generated" '^# Generated by fdwm-theme' "$(head -n1 "$colors")"

# the GRUB theme: the template with every @name@ filled in
theme=$T/repo/grub/theme/theme.txt
expect_match "theme.txt says it is generated" '^# Generated by fdwm-theme' "$(head -n1 "$theme")"
expect "theme.txt: no @name@ left" 0 "$(grep -c '@' "$theme")"
expect "theme.txt: the template's lines, plus the two it starts with" \
    $(($(wc -l <"$T/repo/grub/theme.txt.in") + 2)) "$(wc -l <"$theme" | tr -d ' ')"
expect_match "theme.txt: the desktop is the palette's base" "^desktop-color: \"$fdwm_base\"$" "$(cat "$theme")"

# select_c.png, checked with a CRC-32 of its own rather than gzip's: the
# chunks, their CRCs, and the one pixel in the zlib stream
pngcheck() {
    od -An -tu1 -v "$1" | awk '
        function crc32(from, to,   c, i, k) {
            c = 4294967295
            for (i = from; i <= to; i++) {
                c = xor(c, b[i])
                for (k = 0; k < 8; k++) c = and(c, 1) ? xor(rshift(c, 1), 3988292384) : rshift(c, 1)
            }
            return xor(c, 4294967295)
        }
        function u32(i) { return ((b[i] * 256 + b[i+1]) * 256 + b[i+2]) * 256 + b[i+3] }
        { for (i = 1; i <= NF; i++) b[++n] = $i }
        END {
            for (i = 1; i <= 8; i++) sig = sig " " b[i]
            print "signature" sig
            for (p = 9; p <= n; p += 12 + len) {
                len = u32(p)
                type = sprintf("%c%c%c%c", b[p+4], b[p+5], b[p+6], b[p+7])
                ok = crc32(p + 4, p + 7 + len) == u32(p + 8 + len) ? "crc-ok" : "crc-BAD"
                data = ""
                for (i = p + 8; i < p + 8 + len; i++) data = data " " b[i]
                print type, ok data
            }
        }'
}
png=$(pngcheck "$T/repo/grub/theme/select_c.png")
expect "select_c.png: a PNG" "signature 137 80 78 71 13 10 26 10" "$(sed -n 1p <<<"$png")"
expect "select_c.png: 1x1, 8-bit RGB" "IHDR crc-ok 0 0 0 1 0 0 0 1 8 2 0 0 0" "$(sed -n 2p <<<"$png")"
r=$((16#${fdwm_surface0:1:2})) g=$((16#${fdwm_surface0:3:2})) b=$((16#${fdwm_surface0:5:2}))
s1=$((1 + r + g + b)) s2=$((1 + (1 + r) + (1 + r + g) + (1 + r + g + b)))
expect "select_c.png: one pixel of surface0, stored with its Adler-32" \
    "IDAT crc-ok 120 1 1 4 0 251 255 0 $r $g $b $((s2 >> 8)) $((s2 & 255)) $((s1 >> 8)) $((s1 & 255))" \
    "$(sed -n 3p <<<"$png")"
expect "select_c.png: then the end" "IEND crc-ok" "$(sed -n 4p <<<"$png")"
expect "the images it replaces are gone" "" "$(cd "$T/repo/grub/theme" && ls select_e.png select_w.png 2>/dev/null)"

# palettes and templates it must refuse, each naming the problem
cp "$T/repo/palette" "$T/palette.good"
refuse() {  # refuse DESCRIPTION MESSAGE_REGEX
    out=$(gen)
    local rc=$?
    expect "$1: fails" 1 "$rc"
    expect_match "$1: says why" "$2" "$out"
    cp "$T/palette.good" "$T/repo/palette"
}
sed -i 's/^term_bg .*/term_bg       nosuchcolor/' "$T/repo/palette"
refuse "a name that isn't in the palette" "term_bg: neither a color nor a palette name: nosuchcolor"
echo "base          000000" >>"$T/repo/palette"
refuse "an entry twice" "base is there twice"
sed -i '/^term_cursor /d' "$T/repo/palette"
refuse "an entry the terminal needs is missing" "term_cursor is missing"
sed -i 's/^name .*/name          latte/' "$T/repo/palette"
refuse "no column for the flavor" "no mocha column"
cp "$T/repo/grub/theme.txt.in" "$T/template.good"
echo 'color = "@nosuchcolor@"' >>"$T/repo/grub/theme.txt.in"
refuse "a template color that isn't in the palette" "not in the palette: @nosuchcolor@"
cp "$T/template.good" "$T/repo/grub/theme.txt.in"

out=$(bash "$T/repo/fdwm-theme" 2>&1)
expect "no command: exits 2" 2 "$?"
expect_match "no command: usage" "^usage: fdwm-theme" "$out"

finish
