#!/usr/bin/env bash
# shellcheck disable=SC2016  # stub bodies expand later, not here
# Moving every color into the palette file changed none of them: the commit
# that added the palette, generating Mocha from it, gives exactly what its
# parent had written out by hand. dwm, st, dmenu and slock's config.h
# preprocess to the same code; .bashrc prints the same tty colors and sets
# the same prompt; .xinitrc paints the same desktop; the GRUB theme and the
# kernel's console colors come out the same. Until that commit exists, the
# working tree is checked against HEAD instead.
#
# It reads the repo's history: CI checks all of it out. (Merge the palette
# work with a merge or rebase, not a squash, or its parent is lost.)
# shellcheck source=tests/lib.sh
source "$(dirname "$0")/lib.sh"
sandbox

# the checkout's own git, read only (safe.directory: CI runs the tests as a
# user who doesn't own the checkout)
repo() { git -c safe.directory="$ROOT" -C "$ROOT" "$@"; }

mkdir -p "$T/old" "$T/new" "$T/home"
added=$(repo log --diff-filter=A --format=%H -- palette | tail -n1)
if [[ -n $added ]]; then
    if ! repo rev-parse -q --verify "$added^" >/dev/null; then
        fail "the commit that added the palette has no parent here: fetch the whole history"
        finish
    fi
    echo "  (the palette arrived in $(repo log -1 --format='%h %s' "$added"))"
    repo archive "$added^" | tar -x -C "$T/old"
    repo archive "$added" | tar -x -C "$T/new"
else
    echo "  (the palette isn't committed yet: the working tree against HEAD)"
    repo archive HEAD | tar -x -C "$T/old"
    repo ls-files -z -co --exclude-standard | (cd "$ROOT" && tar --null -T - -cf -) | tar -x -C "$T/new"
fi

# every command below sees only the sandbox home, and fdwm-theme writes
# ~/.config/fdwm/colors.sh there
sandboxed() { env -i HOME="$T/home" TERM="${TERM_:-dumb}" PATH="$T/bin:/usr/bin:/bin" "$@"; }
sandboxed bash "$T/new/fdwm-theme" generate >/dev/null

# dwm, st, dmenu and slock: config.h through the preprocessor, the old one
# with its colors written out, the new one with colors.h; spaces dropped
if command -v cc >/dev/null; then
    for tool in dwm st dmenu slock; do
        old=$(cc -E -P "$T/old/suckless/$tool/config.h" | tr -d ' \t\n')
        new=$(cc -E -P "$T/new/suckless/$tool/config.h" | tr -d ' \t\n')
        if [[ -n $old && $old == "$new" ]]; then
            pass "$tool: config.h preprocesses to the same code"
        else
            fail "$tool: config.h differs after preprocessing"
            diff <(fold -w 100 <<<"$old") <(fold -w 100 <<<"$new") | head -20
        fi
    done
else
    echo "  (skipped the config.h checks: no C compiler)"
fi

# .bashrc, interactive, on a Linux console: the tty colors it prints, then
# its prompt
stub clear 'exit 0'
bashrc() {
    TERM_=linux sandboxed bash --rcfile "$1/dotfiles/.bashrc" -i -c 'printf "\n%s" "$PS1"' </dev/null 2>/dev/null
}
old=$(bashrc "$T/old")
new=$(bashrc "$T/new")
expect "the old .bashrc gives the ttys 16 colors (so this compares something)" 16 \
    "$(head -n1 <<<"$old" | grep -o $'\e\\]P' | wc -l | tr -d ' ')"
expect ".bashrc: the same tty colors, byte for byte" \
    "$(head -n1 <<<"$old" | od -An -c)" "$(head -n1 <<<"$new" | od -An -c)"
expect ".bashrc: the same prompt" "$(tail -n1 <<<"$old")" "$(tail -n1 <<<"$new")"

# .xinitrc with the system's xinitrc.d and polkit agent left out and X
# stubbed: what xsetroot is given. (The old file wrote the color in
# capitals; X reads either.)
stub xsetroot "echo \"\$*\" >>'$T/xsetroot'"
for c in gnome-keyring-daemon xset xss-lock dwm; do stub "$c" 'exit 0'; done
xsetroot() {
    : >"$T/xsetroot"
    sed 's#/etc/X11/xinit/xinitrc.d#/nonexistent#; s#/usr/libexec/#/nonexistent/#' \
        "$1/dotfiles/.xinitrc" >"$T/xinitrc"
    sandboxed sh "$T/xinitrc" >/dev/null 2>&1
    tr 'A-F' 'a-f' <"$T/xsetroot"
}
old=$(xsetroot "$T/old")
expect_match "the old .xinitrc sets the desktop color (so this compares something)" '^-solid #' "$old"
expect ".xinitrc: the same desktop color" "$old" "$(xsetroot "$T/new")"

# the GRUB theme: the generated one, less its "Generated by" lines, and the
# old one with its colors in small letters
theme=grub/catppuccin-mocha-grub/theme.txt
expect_match "the generated GRUB theme says so" '^# Generated by fdwm-theme' "$(head -n1 "$T/new/$theme")"
expect "the GRUB theme: the same, colors and all" \
    "$(sed -E 's/#([0-9A-Fa-f]{6})/#\L\1/g' "$T/old/$theme")" "$(sed 1,2d "$T/new/$theme")"

# the kernel's console colors: install.sh's old vt.default_* lines against
# fdwm-theme's
old=$(sed -n "s/^ *vt_[a-z]*='\(.*\)'$/\1/p" "$T/old/install.sh" | paste -sd' ')
expect_match "the old install.sh had the three vt.default lists" '^vt\.default_red=.* vt\.default_grn=.* vt\.default_blu=' "$old"
expect "the kernel's console colors: the same" "$old" "$(sandboxed bash "$T/new/fdwm-theme" kernel-args)"

finish
